/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DayCard: typeof import('./src/components/DayCard.vue')['default']
    DayCardMenu: typeof import('./src/components/DayCardMenu.vue')['default']
    Entry: typeof import('./src/components/Entry.vue')['default']
    InfiniteScroll: typeof import('./src/components/InfiniteScroll.vue')['default']
    MainScreen: typeof import('./src/components/MainScreen.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
